import "./globals.scss";
import HeadT from "./head";
import Head from "./Navbar";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'], variables: '--font-inter' })
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <HeadT/>
      <body className={`${inter.className}`}>
        {" "}
        <Head />
        {children}
      </body>
    </html>
  );
}
